//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartIsLib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeOOO
    {
        public int EmpId { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string leave { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public string RequestedBy { get; set; }
        public string Status { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
