//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartIsLib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.PerformanceApraisal = new HashSet<PerformanceApraisal>();
        }
    
        public int EmpID { get; set; }
        public string FullName { get; set; }
        public int ManagerId { get; set; }
        public string Status { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Location Location { get; set; }
        public virtual EmployeeOOO EmployeeOOO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PerformanceApraisal> PerformanceApraisal { get; set; }
    }
}
