//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartIsLib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveDestribution
    {
        public int TypeId { get; set; }
        public int Balance { get; set; }
        public int LeaveStructId { get; set; }
    
        public virtual LeaveStructure LeaveStructure { get; set; }
        public virtual LeaveTypes LeaveTypes { get; set; }
    }
}
