//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartIsLib.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformanceApraisal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PerformanceApraisal()
        {
            this.EmployeeGoals = new HashSet<EmployeeGoals>();
        }
    
        public int Id { get; set; }
        public int Rating { get; set; }
        public string RatingType { get; set; }
        public string ManagerComment { get; set; }
        public string EmployeeComment { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeGoals> EmployeeGoals { get; set; }
        public virtual FiscalYear FiscalYear { get; set; }
    }
}
