//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartIsLib.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartIsEntities : DbContext
    {
        public SmartIsEntities()
            : base("name=SmartIsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<DepartmentSlots> DepartmentSlots { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<EmployeeGoals> EmployeeGoals { get; set; }
        public virtual DbSet<FiscalYear> FiscalYear { get; set; }
        public virtual DbSet<Holidays> Holidays { get; set; }
        public virtual DbSet<LeaveStructure> LeaveStructure { get; set; }
        public virtual DbSet<LeaveTypes> LeaveTypes { get; set; }
        public virtual DbSet<Location> Location { get; set; }
        public virtual DbSet<PerformanceApraisal> PerformanceApraisal { get; set; }
        public virtual DbSet<EmployeeOOO> EmployeeOOO { get; set; }
        public virtual DbSet<LeaveDestribution> LeaveDestribution { get; set; }
        public virtual DbSet<SlotHistory> SlotHistory { get; set; }
    }
}
